config/routes.rb
Rails.application.routes.draw do
  resources :sites, only: [:index, :show]

  root 'sites#index'

end

app/models/crawler.rb
class Crawler
  attr_accessor :site, :response

  def initialize(args = {})
    self.site = args.fetch(:site)
  end

  def crawl
    begin
      3.times do
        self.response = RestClient::Request.execute(
          method: :get,
          url: site.url,
          timeout: Rails.configuration.site_timeout,
          open_timeout: Rails.configuration.site_timeout
        )

        break if site_up?
      end
    rescue
    end
    save_status
  end

private
  def save_status
    if site_up?
      site.statuses << Status.create(status: "up")
    else
      site.statuses << Status.create(status: "down")
      OutageMailer.outage_email(site).deliver
    end
  end

  def site_up?
    response.present? && response.code == 200
  end
end

app/models/site.rb
class Site < ActiveRecord::Base
  has_many :statuses
end

app/models/status.rb
class Status < ActiveRecord::Base
  belongs_to :site
  enum status: [ :up, :down ]

  scope :recent, -> { order(created_at: :desc).first(10) }

  validates :status, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/sites_controller.rb
class SitesController < ApplicationController
  expose(:site)
  expose(:site_presenter) { site.decorate }
  expose(:sites)
  expose(:sites_presenter) { SiteDecorator.decorate_collection(sites) }
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Loop Nova" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= yield %>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/sites/index.html.erb
<div class="row">
  <div class="large-offset-4 large-4 columns">
    <h1>Loop Nova</h1>
  </div>
</div>

<div class="row">
  <div class="large-offset-4 large-4 columns">
    <table>
      <thead>
        <tr>
          <td>URL</td>
          <td>Status</td>
          <td></td>
        </tr>
      </thead>

      <% sites_presenter.each do |site| %>
        <tr class="<%= site.background_color %>">
          <td><%= site.url %></td>
          <td><%= site.most_recent_status %></td>
          <td><%= link_to('details', site_path(site)) %></td>
        </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/sites/show.html.erb
<div class="row">
  <div class="large-offset-4 large-4 columns">
    <h1><%= site_presenter.url %></h1>
  </div>
</div>

<div class="row">
  <div class="large-offset-4 large-4 columns">
    <table>
      <thead>
        <tr>
          <td>Status</td>
          <td>Created At</td>
        </tr>
      </thead>

      <% site_presenter.statuses.each do |status| %>
        <tr class="<%= status.background_color %>">
          <td><%= status.status.status %></td>
          <td><%= status.created_at %></td>
        </tr>
      <% end %>
    </table>
  </div>
</div>

<div class="row">
  <div class="large-offset-4 large-4 columns">
    <%= link_to 'home', root_path %>
  </div>
</div>